src/objects/FeatureControl__mdt.object
<CustomObject>
    <description>This custom metadata is used to make trigger as active/inactive as per requirement.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Feature Control</label>
    <pluralLabel>Feature Control</pluralLabel>
</CustomObject>

src/classes/TriggerSwitchDomain.cls
public class TriggerSwitchDomain {
    
    public static Map<String, FeatureControl__mdt> getTriggerSwitch() {
        Map<String, FeatureControl__mdt> triggerSwitchData = new Map<String, FeatureControl__mdt>();
        List<FeatureControl__mdt> triggerSwitch = [
            SELECT DeveloperName,Active__c
            FROM FeatureControl__mdt
        ];
        if(!triggerSwitch.isEmpty()) {
            for(FeatureControl__mdt t : triggerSwitch) {
                if(triggerSwitchData.get(t.DeveloperName) == null) {
                    triggerSwitchData.put(t.DeveloperName, t);
                }
            }
        }
        return triggerSwitchData;
    }
}